services:
  db:
    image: postgres:17.8-trixie # Use a specific version like 'postgres:16'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: aloocord 
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent data storage
volumes:
  pgdata:

